### ISSUE TITLE
INCRIVEL

### ISSUE THREAD

**Issue by samanthaeufrasio** [ciceronascimento/Organizador-de-arquivos#1]
https://github.com/ciceronascimento/Organizador-de-arquivos/blob/45134ae4c03c295f768804cf50696a30978b6639/Sources/Organizador-de-arquivos/main.swift#L1

Amei o código, tomei só um susto com a linhas gigantes achei que tinha bugado meu pc. Fora isso, já organizei minhas pastas com ele!

**Comment by ciceronascimento** [comment]
Valeu pelo feedback Samantha! Vou adicionar formatação na próxima atualização!

**Comment by ciceronascimento** [comment]
Melhoria efetuada! Agora o aplicativo esta formatando a lista de arquivos do diretório e arquivos movidos!  🎉🎉
